
import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import axios from"axios";
import{AppBar,Toolbar,Typography,Container,Box,Button,Paper,Stack,TextField,Checkbox,Table,TableHead,TableBody,TableRow,TableCell,Chip,Dialog,DialogTitle,DialogContent,DialogActions,MenuItem,Grid,Card,CardContent,Alert}from"@mui/material";
const api=axios.create({baseURL:`${import.meta.env.VITE_API_URL || "http://localhost:4000"}/api`}),today=()=>new Date().toISOString().slice(0,10);
function DateBar({date,setDate}){return <Stack direction="row" spacing={2} sx={{mb:2}}><TextField type="date" label="Fecha" InputLabelProps={{shrink:true}} value={date} onChange={e=>setDate(e.target.value)}/><Chip label="Admite fechas pasadas" color="info"/></Stack>}
function App(){const[page,setPage]=useState("asistencia"),[date,setDate]=useState(today()),[rows,setRows]=useState([]),[selected,setSelected]=useState([]),[cash,setCash]=useState({rows:[],summary:{}}),[pending,setPending]=useState([]),[report,setReport]=useState({rows:[],totals:{}}),[from,setFrom]=useState(today()),[to,setTo]=useState(today()),[open,setOpen]=useState(false),[pay,setPay]=useState(null),[amount,setAmount]=useState("20"),[newM,setNewM]=useState({full_name:"",dni:"",category:"integrante"});
const load=()=>{api.get("/attendance",{params:{date}}).then(r=>{setRows(r.data.rows);setSelected(r.data.rows.filter(x=>x.attended).map(x=>x.id))});api.get("/cash",{params:{date}}).then(r=>setCash(r.data));api.get("/pending-attendance",{params:{date}}).then(r=>setPending(r.data))};useEffect(load,[date]);
const saveAtt=()=>api.post("/attendance",{date,member_ids:selected}).then(load),savePay=()=>api.post("/contributions",{date,member_id:pay.id,amount:+amount}).then(()=>{setPay(null);load()}),saveMember=()=>api.post("/members",newM).then(()=>{setOpen(false);load()});
const reportLoad=()=>api.get("/reports",{params:{from,to}}).then(r=>setReport(r.data));useEffect(()=>{if(page==="reporte")reportLoad()},[page,from,to]);
return <><AppBar><Toolbar><Typography sx={{flexGrow:1}}>Control de Agrupación</Typography><Button color="inherit" onClick={()=>setOpen(true)}>+ Miembro</Button></Toolbar></AppBar><Container sx={{py:3}}><Stack direction="row" spacing={1} sx={{mb:3,flexWrap:"wrap"}}>{[["asistencia","Asistencia"],["caja","💰 Caja"],["pendientes","Falta marcar"],["reporte","Reportes"],["historial","Historial"]].map(x=><Button variant={page===x[0]?"contained":"text"} onClick={()=>setPage(x[0])}>{x[1]}</Button>)}</Stack>
{page==="asistencia"&&<><Typography variant="h4">Registrar asistencia</Typography><DateBar date={date} setDate={setDate}/><Paper><Table><TableHead><TableRow><TableCell>Asistió</TableCell><TableCell>Nombre completo</TableCell><TableCell>DNI</TableCell><TableCell>Categoría</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow><TableCell><Checkbox checked={selected.includes(r.id)} onChange={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}/></TableCell><TableCell>{r.full_name}</TableCell><TableCell>{r.dni}</TableCell><TableCell>{r.category}</TableCell></TableRow>)}</TableBody></Table><Box p={2}><Button variant="contained" onClick={saveAtt}>Guardar asistencia</Button></Box></Paper></>}
{page==="caja"&&<><Typography variant="h4">💰 Caja</Typography><DateBar date={date} setDate={setDate}/><Grid container spacing={2} sx={{mb:2}}><Grid size={{xs:12,md:4}}><Card><CardContent>Recaudado<Typography variant="h4">S/ {(+cash.summary.total||0).toFixed(2)}</Typography></CardContent></Card></Grid><Grid size={{xs:12,md:4}}><Card><CardContent>Pendientes<Typography variant="h4">{cash.rows.filter(r=>!r.paid).length}</Typography></CardContent></Card></Grid></Grid><Paper><Table><TableHead><TableRow><TableCell>Miembro</TableCell><TableCell>Estado</TableCell><TableCell/></TableRow></TableHead><TableBody>{cash.rows.map(r=><TableRow><TableCell>{r.full_name}</TableCell><TableCell>{r.paid?<Chip color="success" label={`Pagó S/ ${r.amount.toFixed(2)}`}/>:<Chip color="warning" label="Pendiente"/>}</TableCell><TableCell>{!r.paid&&<Button variant="contained" onClick={()=>setPay(r)}>Cobrar</Button>}</TableCell></TableRow>)}</TableBody></Table></Paper></>}
{page==="pendientes"&&<><Typography variant="h4">Miembros que faltan marcar asistencia</Typography><DateBar date={date} setDate={setDate}/><Alert sx={{mb:2}}>Solo aparecen miembros sin registro de asistencia para esta fecha.</Alert><Paper><Table><TableBody>{pending.map(r=><TableRow><TableCell>{r.full_name}</TableCell><TableCell>{r.dni}</TableCell><TableCell>{r.category}</TableCell></TableRow>)}</TableBody></Table></Paper></>}
{page==="reporte"&&<><Typography variant="h4">Reporte semanal / mensual</Typography><Stack direction="row" spacing={2} sx={{my:2}}><TextField type="date" label="Desde" InputLabelProps={{shrink:true}} value={from} onChange={e=>setFrom(e.target.value)}/><TextField type="date" label="Hasta" InputLabelProps={{shrink:true}} value={to} onChange={e=>setTo(e.target.value)}/></Stack><Grid container spacing={2} sx={{mb:2}}>{[["Reuniones",report.totals.meetings],["Asistencias",report.totals.attendance_records],["Aportes",report.totals.contribution_records],["Recaudado",`S/ ${(+report.totals.total||0).toFixed(2)}`]].map(x=><Grid size={{xs:6,md:3}}><Card><CardContent>{x[0]}<Typography variant="h5">{x[1]}</Typography></CardContent></Card></Grid>)}</Grid><Paper><Table><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Asistieron</TableCell><TableCell>Sin marcar/ausentes</TableCell><TableCell>Aportes</TableCell><TableCell>Total</TableCell></TableRow></TableHead><TableBody>{report.rows.map(r=><TableRow><TableCell>{r.date}</TableCell><TableCell>{r.attended}</TableCell><TableCell>{r.absent_or_pending}</TableCell><TableCell>{r.paid_members}</TableCell><TableCell>S/ {(+r.total).toFixed(2)}</TableCell></TableRow>)}</TableBody></Table></Paper></>}
{page==="historial"&&<History/>}</Container>
<Dialog open={open} onClose={()=>setOpen(false)}><DialogTitle>Nuevo miembro</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Nombre completo" value={newM.full_name} onChange={e=>setNewM({...newM,full_name:e.target.value})}/><TextField label="DNI" value={newM.dni} onChange={e=>setNewM({...newM,dni:e.target.value})}/><TextField select label="Categoría" value={newM.category} onChange={e=>setNewM({...newM,category:e.target.value})}><MenuItem value="integrante">Integrante</MenuItem><MenuItem value="invitado">Invitado</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={saveMember} variant="contained">Guardar</Button></DialogActions></Dialog>
<Dialog open={!!pay} onClose={()=>setPay(null)}><DialogTitle>Cobrar aporte</DialogTitle><DialogContent><Typography>{pay?.full_name}</Typography><TextField fullWidth type="number" label="Monto S/" value={amount} onChange={e=>setAmount(e.target.value)} sx={{mt:2}}/></DialogContent><DialogActions><Button onClick={()=>setPay(null)}>Cancelar</Button><Button onClick={savePay} variant="contained">Registrar pago</Button></DialogActions></Dialog></>}
function History(){const[d,setD]=useState([]);useEffect(()=>{api.get("/history").then(r=>setD(r.data))},[]);return <><Typography variant="h4" gutterBottom>Historial</Typography><Paper><Table><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Miembro</TableCell><TableCell>Categoría</TableCell><TableCell>Asistencia</TableCell><TableCell>Aporte</TableCell></TableRow></TableHead><TableBody>{d.map(r=><TableRow><TableCell>{r.date}</TableCell><TableCell>{r.full_name}</TableCell><TableCell>{r.category}</TableCell><TableCell>{r.attended?"✓":"—"}</TableCell><TableCell>{r.amount?`S/ ${r.amount}`:"Pendiente"}</TableCell></TableRow>)}</TableBody></Table></Paper></>}
createRoot(document.getElementById("root")).render(<App/>);
